s="ATACGTCATTTCAAATAGCCGCGGCAAATAGGCAAATAGGTCAAATAGCAAATAGTCTTCAAATAGCCAAATAGCAAATAGCAAATAGGACCCCAAATAGAACAAATAGTGCAAATAGCAAATAGCGCACCCAAATAGGCGTGGCAAATAGTTGGCAAATAGAAAACAAATAGCGCAAATAGCCAAATAGTGATTGTTCTCAAATAGGCAAATAGTACAAATAGTGCAAATAGAGGACCAAATAGCCGAGTCACATTTCAAATAGCCCAAATAGACCCCTGGGCAAATAGTCGGCAAATAGATCAAATAGCCAAATAGCAAATAGGCAAATAGCAAATAGCCAAATAGCTCAAATAGCACACCAAATAGGCAAATAGAATTTAAAGCCAAATAGGAATCAAATAGCAAATAGCAAATAGTCTGGTCCAAATAGCGCAAATAGGTACTTCAAATAGGTCAAATAGCCCAAATAGTCAAATAGAGATGGAGCAAATAGAGCAAATAGGCACACAAATAGACAAATAGGTCCAAATAGACCAGCAAAATCAAATAGCCCAAATAGCAAATAGGGACTCAAATAGCAAATAGGTCCAAATAGTCGAACGCAAATAGAAGCATCAAATAGGAACCAAATAGCAGCCAAATAGCAAATAGACCACAAATAGACAAATAGATTAGCCGTCCAAATAGACAAATAGACAAATAGGCAAATAGAGCAAATAGCGCGTAAATCAAATAGCAAACAAATAGCACAAATAGTACAAATAGGACAAATAGACAAATAGCACCAAATAGTCGCAAATAGACTG"
t = "CAAATAGCA"

found= []
temp = ""

for i in range(len(s)-len(t)):
    for g in range(len(t)):
        temp += s[i+g]
    
    if temp == t:
        found.append(i+1)
    else:
        temp = ""

#upraveni do answer formatu
answer =""
for k in found:
    answer += " "+str(k)
print(answer)